# Generated by Django 5.2.7 on 2025-11-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='users',
            new_name='user',
        ),
    ]
