# Generated by Django 5.2.7 on 2025-11-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_users_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='descrption',
            new_name='description',
        ),
    ]
